### PR TITLE
Ch 5 - Added Minimax and Alpha Beta visualizations

### PR DESCRIPTION
**Pull request by regalhotpocket**

### CODE REVIEW

**Comment by redblobgames** [comment]
This is pretty cool — I like how I can use the slider to rewind.

Minor readability suggestions: black text on red is harder to read than white text on red. It might be useful to use dark/light as a way to show which nodes have been evaluated. Instead of black-on-red vs black-on-orange, maybe white-on-red vs black-on-orange.

It might be nice to show which of the child nodes was chosen as the min/max at each level, either by highlighting that node, or by making the line between them thicker.

For Alpha-Beta pruning, I think it would help to show the current pruning condition. For example when evaluating the minimize nodes, you're pruning the rest once you find a node < 6, so you could put something like "prune if < 6" somewhere.

**Comment by regalhotpocket** [comment]
Thanks for the feedback. I worked on what you suggested, and for the Alpha-Beta pruning I tried displaying it in the same notation as the book.

**Comment by redblobgames** [comment]
Looks cool. Minor suggestions:

- the white text looks nice with the black outline but the black text looks worse with the black outline; can you put the black outline only on the white text?
- by the time the reader has gotten to the second diagram the animation is in a random position; it would be nicer if the animation are *stopped* when the page loads, and don't start until the reader starts them

**Comment by regalhotpocket** [comment]
I choose to leave the animation auto-playing from the start, but added a jquery function to detect when the animation scrolls into view before starting it.

I also worked with the colors some more. I choose a gradient of colors to show the state of the node from untouched->processing->current. This also helps the text stay readable.

**Comment by redblobgames** [comment]
This looks nice! :)

**Pull request merged**
