### PR TITLE
First prototype of Node expansion visualization

### PR DESCRIPTION
**Pull request by Rishav159**
@redblobgames This adds a basic prototype for the node expansion visualization we were thinking about. Kindly review this and suggest how I should proceed further.
The PR can be merged only after the particular visualization is completed.
Progress on #57

### CODE REVIEW

**Comment by redblobgames** [comment]
The diagram looks pretty good. The implementation of `drawGraph()` has a click handler that invokes `drawGraph()` again. Each time you call the function, it's creating new svg nodes. You'll end up with thousands of svg nodes, with each circle and line being drawn multiple times. Either remove all the existing nodes before you redraw, or generate the circles and lines once, and reuse them (change the color of the existing node, add/remove event handlers).

Minor things to make it look prettier (you don't have to do these now):

* For the key on the right, put the colored box before the text. That way the boxes will line up.
* For the Frontier Nodes area on the right, try a light gray background instead of a dark black line around the area.
* The black label on the expanded/frontier nodes are hard to read. Either change the text to white or change the colors to be lighter (maybe "hsl(0,50%,70%)" and "hsl(200,50%,70%)") (btw, using hsl colors instead of #rrggbb will make it easier to lighten/darken, or construct related colors)

**Comment by Rishav159** [comment]
Ok. I will keep these things in mind. I will implement the suggested changes. 
Is this visualization good enough for explaining how nodes expand? 
I was thinking about another visualization where we will not show the unexplored nodes to give the users an example on how the search agent perceives the environment (ie The search nodes only knows about the nodes that either has been expanded or present in the frontier). This may prove helpful to give an intuition on the search process from the eyes of the search agent. What do you think? @redblobgames

**Comment by redblobgames** [comment]
Yes, I think the visualization is pretty good for showing how nodes expand. I agree, hiding the unexplored nodes would explain to the reader that the search algorithm cannot see the entire graph at the beginning. That seems like a great second diagram, or maybe it is so useful that we don't need the first one anymore. One way to implement both diagrams with the same code would be to pass in parameters for coloring the nodes and edges (both color and opacity), and then for the second diagram you can use a very low opacity on those nodes and edges.

**Comment by Rishav159** [comment]
I think having both the diagrams should fit our purpose better. I will try to make sure we can have a common code for both of them. 
I was trying to create a function that can generate random graphs for the visualizations. The nodes will have a minimum distance between them and the edges will only be created among nodes which are close to each other. It turned out to work pretty well. We might not need it for this particular visualization. Maybe later. What do you think?

**Comment by Rishav159** [comment]
@redblobgames The changes to the first visualization as per the suggestions is completed. I have reused the existing SVG elements for the graph and redrawing the frontier nodes SVG elements on the right side.
Kindly review.

**Comment by Ghost---Shadow** [comment]
I have found that instantiating all the `Rectangles`, `Circles` etc during initialization and then just translating them in the loop is far more computationally efficient.

**Pull request merged**
