### PR TITLE
Ch 5 - changed alphabeta to alphaBeta in index.html

### PR DESCRIPTION
**Pull request by regalhotpocket**
I forgot to fix this bug in my original commit for chapter 5:
https://github.com/aimacode/aima-javascript/issues/78

Edit
I also added a feature for chapter 3 requested here:
https://github.com/aimacode/aima-javascript/issues/119

### CODE REVIEW

**Comment by redblobgames** [comment]
Cool, the hover effect is nice. For bug #119 we'll also want to make the same thing across diagrams. Do you want to make that change here, or should I check in this change for the node expansion diagram, and then we can leave that bug open for the other diagrams?

**Comment by regalhotpocket** [comment]
It was an easy fix, I'll work on implementing it for others.

**Comment by regalhotpocket** [comment]
I added the zoom effect for dfs, bfs, uniform search, and A*.

**Comment by redblobgames** [comment]
Looks great! For the A* diagram (which was implemented by a different author) it seems to be behaving differently — it's changing the circle on the right to red instead of changing its size like the other diagrams.

**Comment by regalhotpocket** [comment]
Yeah they use completely different methods of rendering. A* is all inline html and css, so if I expand a node it messes up the entire diagram. I could rewrite it all in Two.js, or maybe I can change the other diagrams to turn red instead of expanding.

**Comment by redblobgames** [comment]
Thanks! Consistency is good. I did like the other style better but this works too. Which do you prefer?

**Comment by regalhotpocket** [comment]
Honestly, if both are good then I would want to stick with the colors as rewriting the A* would be a lot of work for such a little improvement.

**Comment by redblobgames** [comment]
Ok, great, I will check it in!

**Pull request merged**
