### PR TITLE
Ch 7 - The start of Wumpus World

### PR DESCRIPTION
**Pull request by AnimeshSinha1309**
### Description
I have implemented a version of Wumpus World for Chapter 7, replacing the older game. The previous game had no scope for understanding of strategy, it was just to navigate to gold. This version hides where the Gold is, and where Wumpus or the Pits are, and forces the user to *find a strategy* using the **measurements**.

### Major Changes
I have implemented this game in TypeScript, so it would need transpiling to JavaScript. Have set it up in the Gulp config.

### CODE REVIEW

**Comment by AnimeshSinha1309** [comment]
This is what my current version looks like.
screenshot from 2018-12-17 03-23-32

**Comment by AnimeshSinha1309** [comment]
Using **TypeScript** in this porting of the code, but it's just one file and transpiles directly to JavaScript, so will not be an issue right now. Over the long term it would be great if we could restructure the whole code base. Get to *Bootstrap 4, use webpack and split the TypeScript files* into multiple segements, and just make it easier to implement each chapter more independently.

**Comment by norvig** [comment]
I don't understand -- if this is about playing Wumpus, why are there changes related to a tic-tac-toe board?  Thanks for the diagram with "This is what my current version looks like." I think what it should look like is to have icons of the explorer, the wumpus, the pit, the gold, breeezes, etc. There should be one view that shows the whole state of the world, one that shows what the agent perceives this turn, and one that shows the agent's model of the world.

**Comment by AnimeshSinha1309** [comment]
The files on the Tic-Tac-Toe thing were a mistake, had used the same branch. Deleted those commits now. 
I will edit the game, add the view that shows the whole state of the game and show the inferences. But that's gonna take me a few days. The current version does show a banner when you lose / win, a demo of the game is here: [https://researchweb.iiit.ac.in/~animesh.sinha/7-Logical-Agents/](https://researchweb.iiit.ac.in/~animesh.sinha/7-Logical-Agents/).

**Comment by redblobgames** [comment]
(Observation) It's going to be interesting when each new contributor wants to use a new set of tools (typescript, browserify, gulp, webpack, babel, or whatever) instead of following what the project already has chosen to use. It will be *especially* interesting when we get multiple contributors who want to rewrite each others' code to use their own incompatible favorite tools.

**Comment by AnimeshSinha1309** [comment]
> (Observation) It's going to be interesting when each new contributor wants to use a new set of tools (typescript, browserify, gulp, webpack, babel, or whatever) instead of following what the project already has chosen to use. It will be _especially_ interesting when we get multiple contributors who want to rewrite each others' code to use their own incompatible favorite tools.

It's not that I want to use random tools, **Gulp is already there**, and I can choose to port everything to JavaScript, but it's the same thing as TypeScript. With the gulp config, it does not hurt the project at all, you can run it immediately, and make the code cleaner. And **webpack I do not need**, I was just confused. As far as rewriting the code goes, I am not trying to do that. It's just more convenient to port stuff to the new version of the framework (Bootstrap v4.1) because everyone is using it.

@redblobgames you or anyone else objects to these I will not make those changes, they are not integral to what I do. I can **even pull back on the TypeScript**, and just use the transpiled JavaScript, but I am sure we can agree that it will hurt the readability of the code. Also as a new developer I prefer the strongly typed syntax. *If you have any specific advice / objections*, please tell me, and I will try my best not to do those things.

**Comment by redblobgames** [comment]
My generic advice for all open source projects, not only this one, is that you should follow *their* preferences instead of *your* preferences, unless you've first gotten permission from the maintainers to use something different.

I'm no longer working on this project so you'd want to ask Peter and Sam. The last time I worked on this project, we removed all uses of Gulp (in early 2017), and the gulp file is ready to be deleted.

(And in case you're interested in Google Summer of Code: contributing a diagram here is probably not useful, as described in the wiki)

**Comment by AnimeshSinha1309** [comment]
Okay, sorry, did not realize gulp would be removed and thought it would be really easy to port TypeScript to JavaScript. It's not that, it seems pretty tedious. If this is really a problem, I can spend some time and actually get rid of the TypeScript, but any other way would be so much easier. Please review and advice @norvig.

**Comment by norvig** [comment]
I'm not against typescript, if you can describe an easy way to make it work within the constraints of github. 

I don't know anything about gulp, except that it was decided not to use it last year.

I don't think it is acceptable to have a display that introduces new colors for cells, with an external key. Use icons/sprites similar to the ones in the book. They can also have colors if you want, but they have to be understandable without an external key.

**Comment by AnimeshSinha1309** [comment]
Thanks, if TypeScript is not an issue then it already works with the GitHub / Gulp framework with no modifications. If gulp is removed, there may be some issues, but any build tool, if not gulp then webpack can solve it and even in it's absence we can manually compile and send (not suitable for quick builds).

As far as the icons go, I will do them, though I am really bad at getting vector graphics. I will have to make the model filtering a little bigger, which I didn't really want to cause it showed in one image how the computer thinks, and it may be hard to fit all icons (upto 3) cleanly in the grid. I will try to keep it clean and get the icons, if you have thoughts on what to do with the **icons in model filtering**, please do.

**Comment by AnimeshSinha1309** [comment]
No no, this is just the art that was already in the book. I just got them here from the book.

**Comment by AnimeshSinha1309** [comment]
Hello everyone, could someone please review this Pull request and see if this okay to be merged.

**Comment by redblobgames** [comment]
Closing for inactivity, and because there's nowhere to put this right now. The current goal of the project (as of 2018) is to build visual explanations of concepts, not playable demos or games. This might be useful in a larger context of an explanation that uses wumpus world, but I think no one is working on one right now.

**Pull request closed without merging**
