### PR TITLE
Adds Australia Map coloring problem

### PR DESCRIPTION
**Pull request by Rishav159**
This commit: 
- Adds a map coloring problem with a map of Australia. The states can be colored by choosing a color from a palette and then clicking on the state. The reader is asked to color all the states following the condition that no two neighboring states can have the same color.
- Increases width of the content div in index.html of Chapter 4. This makes the content more clear.
Development in #88

### CODE REVIEW

**Comment by redblobgames** [comment]
Nice diagram! The code for `drawText`, `bindClicks` would be cleaner if you made a list of areas like

    let territories = [
        ['#NT', 'NT', 1/7.5, 1/6],
        ['#WA', 'WA', 1/16, 1/4],
       …
    ]

That way you can loop through them. Similarly, `drawPalette` would be simpler if you had a list of colors in the palette.

**Comment by redblobgames** [comment]
Color suggestions: try changing hsl(___,100%,50%) for the main map areas to hsl(___,50%,80%). It will make the text easier to read.

For the text, right now it's inheriting the stroke and fill colors from the parent `<g>`. I suggest `stroke:none;fill:black` on them to make them solid.

**Comment by Rishav159** [comment]
Updated as per reviews. However, I am not so sure about the color suggestion.
Here is a comparison: 
This is with hsl(___,80%,70%)
screenshot from 2017-06-24 20-27-55
This is with hsl(___,50%,80%)
screenshot from 2017-06-24 20-28-35

After fixing the text colors, I think hsl(___,80%,70%) looks better. I have updated with the new colors. What do you think ?

**Comment by redblobgames** [comment]
Looks good! The text is readable now :)

**Pull request merged**
