### PR TITLE
A new list of tasks to be completed

### PR DESCRIPTION
**Pull request by Rishav159**
The current CONTRIBUTION.md file only has the list of pseudo-codes and its status. But since for the javascript repository, there may be more/fewer visualizations, I propose a new list of tasks based on the concepts that need to be covered from the book. 
Note:
- Current list only has chapters 1-4 covered. It will be updated soon.
- The list is made in my perspective on what concepts could help with a visualization. Contributors are more than welcomed to put forward their views and update the list.
- This is **not** a list of visualizations. For example, some concepts may not need a visualization or one visualization may cover multiple concepts.

I will add a link to this list in the README if this gets merged. 
Please review.

### CODE REVIEW

**Comment by Ghost---Shadow** [comment]
Looks good, but I will wait for @redblobgames to validate.

**Comment by Rishav159** [comment]
@Ghost---Shadow Yes you are right. It is important to have visualizations wherever it will help the students grasp a concept well and not just as a support for the algorithms. 
Since the underlying js is not important, I guess we can have different implementations for the actual working of the visualization and for showing the user on the page. 
I will wait for @redblobgames to validate this pr before continuing to work on this.

**Comment by redblobgames** [comment]
I agree that (part of) the current CONTRIBUTION file is organized by pseudocode, and we should change that given the change in focus to visualizations. Since some concepts/visualizations will span multiple algorithms in a chapter, I think it is unlikely that we can divide up the work more finely than chapter.

I am not optimistic that any master list of tasks we come up with _now_ will work. I think we will first need to experiment to learn what kinds of concepts work well with interactive visualizations. It may be that some concepts are hard to visualize, or it may be that some concepts can be visualized but there is no benefit to making it interactive. It may be that each chapter is so different that it needs to be evaluated separately.

Since the goal of the CONTRIBUTION file is for people to see what's being worked on, and we aren't likely to assign one chapter to multiple people, what would you think of us changing the file to list chapters instead of algorithms? When someone signs up to work on a chapter, we can discuss ideas for that chapter — maybe one github issue or wiki page per chapter.

**Comment by Rishav159** [comment]
I like the idea of having separate issues for separate chapters with a proper label. Since issues can be assigned to people, it would serve as a proper record of who is working on what part.
Regarding the list, I see your point. We should probably experiment with one chapter before trying to make a master list. Since I am focused on the 3rd chapter, will it be a good idea for me to go forward and try to implement some visualizations of that chapter? We can review that later and then come up with better plans on how to go around dealing with other chapters too. 
I am closing this pull request for now.

**Pull request closed without merging**
