### PR TITLE
Add logo image in title bar

### PR DESCRIPTION
**Pull request by prakamya-mishra**
I have added the logo image to title bar to all the html pages:

screen shot 2017-09-06 at 11 42 53 pm

### CODE REVIEW

**Comment by prakamya-mishra** [comment]
Is there any problem with this?

**Comment by prakamya-mishra** [comment]
Can you merge this so that I can give other PR's?

**Comment by Rishav159** [comment]
@redblobgames Can you please review this?

**Comment by redblobgames** [comment]
@Rishav159 I don't know how to evaluate this because I don't know what the intent of the design is (it was put in place before I joined this project). If @prakamya-mishra is doing this for an open issue then please mention the issue and if doing this in response to a discussion with whoever wanted this change, then please have that person review it.

@prakamya-mishra if you keep this in a separate branch then it won't affect your other PRs. I'm happy to review the algorithm visualization PRs.

**Pull request closed without merging**
