### PR TITLE
Implements Depth Limited Search, Iterative Deepening dfs and adds comments for other files

### PR DESCRIPTION
**Pull request by Rishav159**
This commit does the following: 

- **Implements Depth-Limited Search**
The graph was changed to a tree structure so it resembles a search tree. The user can decide the limit using a select input box, the algorithm traverses the graph with that limit.

- **Implements Iterative Deepening Depth-First Search**
The range bar from the dls is disabled for the user to change and it automatically increases from 0 to 5 in a certain interval. The user can see how the tree is traversed accordingly.

- **Adds comments to other files of chapter 3**
Improves readability of other files by adding comments.

Progress on #57 
Please review

### CODE REVIEW

**Comment by Rishav159** [comment]
@redblobgames  Replaced select with a slider.
The main aim of this diagram is to show that the depthLimitedSearch explores the search tree in a limited way. It only expands the nodes which are present at a depth below or equal to the given limit.
The main purpose of this diagram is to lay out the limitation concept before introducing to iterative depth limited search.

**Comment by redblobgames** [comment]
1. In the text on the page, I don't know what you mean by "optimal". May remove that text (because we are expecting the book to explain it) or define optimal in this situation
2. In the text on the page, change "cutt-off" to "cut-off"
3. There's both animation and the slider, and changing the slider will restart the animation. It might be ok to have a diagram that doesn't have animation here. We have already showed earlier on the page how depth first search works, so the main idea here is that there is a limited depth. Could you try drawing things without the animation? That way as soon as you change the slider it shows the entire tree that is searched. I think this will work better when you get to iterative deepening, because the animation in that diagram can be changing the depth instead of showing the animation you have now

**Comment by Rishav159** [comment]
> In the text on the page, I don't know what you mean by "optimal". May remove that text (because we are expecting the book to explain it) or define optimal in this situation

Yes it makes sense. The word optimal might confuse the users.

>In the text on the page, change "cutt-off" to "cut-off"

Will fix this typo.

>There's both animation and the slider, and changing the slider will restart the animation. It might be ok to have a diagram that doesn't have animation here. We have already showed earlier on the page how depth first search works, so the main idea here is that there is a limited depth. Could you try drawing things without the animation? That way as soon as you change the slider it shows the entire tree that is searched. I think this will work better when you get to iterative deepening, because the animation in that diagram can be changing the depth instead of showing the animation you have now

Okay. I agree with your view. Since the iterative deepening is so much similar to this, I am thinking about implementing it in this PR itself. I simply have to disable the range input for the user and increase the range automatically in each iteration.

**Comment by redblobgames** [comment]
> Since the iterative deepening is so much similar to this, I am thinking about implementing it in this PR itself. I simply have to disable the range input for the user and increase the range automatically in each iteration.

Sounds good. This is like some of the earlier patterns on the page where we ask the reader to perform the action manually first, and then we show how the algorithm performs it automatically. In this case the reader is changes the depth manually at first, and then iterative deepening changes it automatically.

**Comment by Rishav159** [comment]
Added Iterative Deepening depth-first search and updated depth-limited-search according to the review

**Comment by redblobgames** [comment]
Since depth limited and iterative deepening are so similar in structure, can you make a visualization function or class that makes the visualization, and then takes the *depth* as a parameter for redrawing it?

* Then in the depth limited case you'll have a slider that calls redraw with the slider value.
* In the iterative deepening case you'll have a setInterval that changes the value and calls redraw.

Other than those two differences (maybe <5 lines for the slider and <10 lines for the timer) the code would be the same. This kind of structure will be useful for future diagrams too — there will be parameters (*depth limit* in this case) that we want to control in multiple ways (slider or animation or calculated in some other way), and we want to structure our diagrams so that how it uses the parameter is separate from how the parameter is controlled.

Also, please put the bootstrap-slider file into a third-party/ folder with a readme that includes where you got it and what the license is. We need to separate the code we write for aimacode (which gets the aimacode open source license) from libraries we are using from elsewhere, which have their own license.

**Comment by Rishav159** [comment]
Updated respecting the reviews.
The important functions for the depth limited and iterative deepening diagrams are made into one function and written in helpers.js
This makes the c_depthLimitedSearch.js and c_iterativeDeepeningSearch.js more compact and clear.

Regarding the bootstrap slider, I was experimenting with it and turns out the basic html slider works fine and hence I have removed it.

**Comment by redblobgames** [comment]
Cool. How do you like the visualization now? Do you feel it is a good match for the concepts?

* If you change `$('#limitSelector').change(function() {` to `$('#limitSelector').on('input', function() {` it will run as you move the slider instead of waiting until you let go of the slider

**Comment by Rishav159** [comment]
Updates made with respect to changes suggested.

I feel the current diagrams explains the concept of limit depth-first search pretty well. What do you think ?

**Comment by Ghost---Shadow** [comment]
The currently hosted version at gh-pages has a typo. If you have already fixed it, disregard this comment.

"At any point of time in the process of a Uniform Cost Search, the costs of the `explroed` nodes are always less than or equal to the costs of the frontier nodes (and also unexplored nodes as a matter of fact)."

**Comment by Rishav159** [comment]
@Ghost---Shadow  Thanks for pointing out the typo. It was a really silly mistake!
- Fixes typo
- Squashed commits

**Comment by redblobgames** [comment]
Looks good.

**Pull request merged**
