### PR TITLE
Adds Breadth First Search Visualization

### PR DESCRIPTION
**Pull request by Rishav159**
This adds the first prototype of Breadth First Search visualization for Chapter 3
Progress on #57 
Please Review @redblobgames

### CODE REVIEW

**Comment by redblobgames** [comment]
Thoughts on the visualization:

The node expansion and breadth first search visualizations can be very similar. The main difference is that with node expansion, the event we're waiting for is for the reader to choose a node, and for breadth first search (and also later, depth first), the event we're waiting for is the animation timer (or maybe a slider, or for the reader to click on a "next" button) and the node is chosen by the algorithm.

1. The Frontier Nodes area on the right and the FIFO Queue area on the right can be shared and use the same style. If it is easy to do that now, do it now, and otherwise it can wait.
2. The FIFO Queue area shows a node in green but the diagram on the left does not; this makes it harder to see the connection.
3. This may be a diagram where more animation will help the reader. This is something we can look at later.

Thoughts on the code:

1. I looked at the aima-java repository for [graph search](https://github.com/aimacode/aima-java/blob/AIMA3e/aima-core/src/main/java/aima/core/search/framework/qsearch/GraphSearch.java) and also the aima-python repository for [graph search](https://github.com/aimacode/aima-python/blob/master/search.py) and they are not using all-caps names the way the pseudocode does. So I think we don't need to use all-caps for the javascript code, but instead use local javascript naming conventions. You don't have to change this now; we can look at it later.
2. You have many inconsistencies in the use of spaces and puncutation. For example `for(var i=0;i < ` vs `for(var i=0; i <`, or using semicolons after some statements and not others, or using spaces after some colons but not others. When we get closer to the start of gsoc we should look at tools like [jsbeautifier](http://jsbeautifier.org/) to make all the formatting consistent.
3. Can breadth first search reuse nodeExpansionAgent and call `expand(frontier[0])`? This may allow us to make breadth first search three lines of code, like it is in the python version. (Somehow the Python version is 3 lines and the Java version is 86 lines…)  If you can structure the code so that breadth first search is 3 lines of code, then depth first search will also be 3 lines of code, by calling `expand(frontier[frontier.length-1])`.

The code can be cleaned up once we have found the right visualizations; it's not important to do it now. The visualization you have looks good except it's missing the green "next expansion" on the left side.

**Comment by Rishav159** [comment]
> The Frontier Nodes area on the right and the FIFO Queue area on the right can be shared and use the same style. If it is easy to do that now, do it now, and otherwise it can wait.
Yes. They can be shared the same CSS property by adding class but then again I was more focused on getting the visualization right as we can do these things later once we have figured out what visualizations we need.

> The FIFO Queue area shows a node in green but the diagram on the left does not; this makes it harder to see the connection.

I will make the necessary changes
>This may be a diagram where more animation will help the reader. This is something we can look at later.
I agree this diagram needs more animations. We can come up with something.

>I looked at the aima-java repository for graph search and also the aima-python repository for graph search and they are not using all-caps names the way the pseudocode does. So I think we don't need to use all-caps for the javascript code, but instead, use local javascript naming conventions. You don't have to change this now; we can look at it later.

I did not notice that other repositories are not following the same convention. I just used it because Norvig told me earlier that its important to make the code as similar to the pseudocode as possible.

> You have many inconsistencies in the use of spaces and punctuation. For example for(var i=0;i < vs for(var i=0; i <, or using semicolons after some statements and not others, or using spaces after some colons but not others. When we get closer to the start of gsoc we should look at tools like jsbeautifier to make all the formatting consistent.

I will try to be more consistent with my code. I will also look into jsbeautifier.

> Can breadth first search reuse nodeExpansionAgent and call expand(frontier[0])? This may allow us to make breadth first search three lines of code, like it is in the python version. (Somehow the Python version is 3 lines and the Java version is 86 lines…) If you can structure the code so that breadth first search is 3 lines of code, then depth first search will also be 3 lines of code, by calling expand(frontier[frontier.length-1]).

This confusion also came because I believed I needed to make the breadthFirstSearch code as close to the psuedocode as possible. I was aware that the nodeExpansion code could be reused and the breadthFirstSearch simply needs to return which node to expand next. If i make the requested changes, we won't have the code for the user to see in the page. So, would we write it somewhere else just for the user to see(and not actually used) or we just may skip showing the users actual code?(because they can always refer to the book for psuedocode)?

Also, as we are getting close to GSOC, I am having concerns on how much chapters should be included as part of the proposal. The proposal shall require from me the details of the implementation as well as verified by the mentors. What do you think? @redblobgames

**Comment by redblobgames** [comment]
For now let's not worry about making the code similar to the pseudocode, and skip showing the code to the reader. Most of the readers who want to see visualizations will be using the python or java versions anyway, and they will not care about the javascript code. It will be much more important to make the visualizations (they will be useful for all AIMA readers).

**Comment by Rishav159** [comment]
Okay. I will make the corresponding changes.

**Comment by Ghost---Shadow** [comment]
Please squash your commits, it makes resolving merge conflicts a lot easier.

**Comment by Rishav159** [comment]
@redblobgames I have updated the requested changes. Also added the depthFirstSearch as it is very similar to the breadthFirstSearch. Please review.
@Ghost---Shadow I will keep that in mind from the next PRs. Thank you

**Comment by Ghost---Shadow** [comment]
You can squash all commits for this pull request itself.
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by Rishav159** [comment]
@Ghost---Shadow Done.

**Pull request merged**
