### PR TITLE
Created Homepage and directory structure

### PR DESCRIPTION
**Pull request by Ghost---Shadow**
Here is the home page
http://ghost---shadow.github.io/aima-javascript/

Each folder I have created will have all javascript files associated with that chapter and one index.html for demonstration on HTML canvas.

Mr. Prabod might have to move his js to corresponding folders.

### CODE REVIEW

**Comment by Ghost---Shadow** [comment]
I added just HTML and CSS. As far as I know, they cannot be unit tested.

**Comment by Ghost---Shadow** [comment]
I cannot issue pull request with aimacode/gh-pages, histories dont match.
Please delete aimacode/gh-pages and fork it again from master.

**Comment by norvig** [comment]
Sorry, I missed seeing that this request was here. I will delete aima-javascript/gh-pages and fork it again from aima-javascript/master.

**Comment by norvig** [comment]
OK @Ghost---Shadow ; should be ready now.

**Comment by norvig** [comment]
@Ghost---Shadow could you resolve conflicts and resubmit? Thanks!

**Pull request closed without merging**
