### PR TITLE
Ch 22- Add IR score function

### PR DESCRIPTION
**Pull request by prakamya-mishra**
This is with reference to #103 .

### CODE REVIEW

**Comment by prakamya-mishra** [comment]
@redblobgames this model will work for any corpus in the document. At this time i did not find any so we can add it later.

**Comment by redblobgames** [comment]
The code treats each document separately. What would have to be done to the code to support 4 documents?

**Comment by prakamya-mishra** [comment]
This code is only for the visualisationof three documents only. For 4 documents new set of variables will have to be made to calculate it's BM25 score.

**Comment by redblobgames** [comment]
Even if you're only going to have three documents, it would be a lot less code if you supported any number of documents. You have a lot of duplicate code in there. And a lot of logging statements too.

**Comment by prakamya-mishra** [comment]
Ok @redblobgames, I will refactor the code.

**Comment by prakamya-mishra** [comment]
@redblobgames have removed the logs but while trying to reduce the code size the results were going wrong. So I am not able to reduce code size.If you want me to add any other section to it then please let me know i will try to do it.

**Comment by prakamya-mishra** [comment]
@redblobgames what should i do now?any suggestions?

**Comment by prakamya-mishra** [comment]
@redblobgames  should work on this more or should i start with the next section?

**Comment by redblobgames** [comment]
@prakamya-mishra I think you should figure out why you need separate code for each document instead of sharing the same code for all the documents. A ranking might involve thousands of documents. You should not have to duplicate the code thousands of times to make it work with thousands of documents.

**Comment by prakamya-mishra** [comment]
ok will do that 👍

**Comment by prakamya-mishra** [comment]
Sorry ,I was busy with my exams. I will again start working on this now.

**Comment by prakamya-mishra** [comment]
I am closing this PR and will give a new one when it is complete.

**Pull request closed without merging**
