### PR TITLE
Ch 22 - Add IR scoring function

### PR DESCRIPTION
**Pull request by prakamya-mishra**
I have made it dynamic in wich you can add any number of documents like you asked for and reduced the code repitation.

### CODE REVIEW

**Comment by prakamya-mishra** [comment]
This is with reference to #103 .

**Comment by prakamya-mishra** [comment]
@redblobgames is there anything that you want me to improve here?

**Comment by redblobgames** [comment]
The code is nicer, thanks!

The visualization could use some improvements:

- The BM25 shows the *numbers*. Is that helping the person reading the AIMA textbook? What is the main idea we're trying to show here — is it how BM25 is calculated, or is it to show which document matches best? If it's about the calculation, then it would be useful to show more details about the calculation. If it is to show the document matches, it would be useful to show the actual matches in the documents.
- You're displaying the query and the documents as *html strings* instead of *text strings*. This means if someone's document is `Is a<b ? If so then we must try again` it will display incorrectly.
- Most readers will not spend the time to find documents to put into the system. It would be good to have the page start with set of example documents, and then the reader can use Reset if they want to put in their own.
- When you click Submit on the query you have to them click Get IR Scoring to see the result. It would be simpler if you did not have to click both buttons. You can recalculate the IR Scoring when the query is submitted and also when documents are changed.
- Make the queries case-insensitive so that they match a word at the beginning of a sentence ("_The_ cat …") and also the word in the middle ("a dog chases _the_ cat")

**Comment by prakamya-mishra** [comment]
Ok, I will work on it ,Thanks for your input 😄 .

**Comment by redblobgames** [comment]
Closing for inactivity.

**Pull request closed without merging**
