### PR TITLE
Ch 2 - Add table of contents and links to sention #98

### PR DESCRIPTION
**Pull request by prakamya-mishra**
This is with reference with issue #98 .
I have added a Table of contents in Ch 2. If this looks good then please merge this pull request and let me know then I will add this to all the chapter.

### CODE REVIEW

**Comment by redblobgames** [comment]
Hi, this looks good (but title is misspelled). I think it would be better to use some kind of names instead of numbers. The reason is that if someone adds a diagram between 1 and 2, it means all the numbers have to be changed. That by itself is not a big problem on the page itself, but it causes all links to the page to be broken. For example if someone links to http://aimacode.github.io/aima-javascript/2-Intelligent-Agents/#tittle-3 because they want to link to the Rules to Follow diagram, and then we change the page to have a new diagram between 1 and 2, then 2 would become #tittle-3 and 3 would become #tittle-4. And then the link to #tittle-3 would now point to the wrong diagram.

If we had names, then none of the existing links have to be changed. For example the names could be 

1. `#vacuum-cleaner-problem`
1. `#simple-cleaning-robot`
1. `#rules-to-follow`
1. `#performance-measures`

**Comment by prakamya-mishra** [comment]
ok I will work on this.

**Comment by prakamya-mishra** [comment]
Which title is misspelled? if this is okay then you can merge this and I will do this for all other chapters.

**Comment by redblobgames** [comment]
The id "tittle" was misspelled (instead of title), the word "sention" in the change list should be "section", and the word "cornors" should be "corners". But the "tittle" thing doesn't matter anymore now that the ids are different. Thanks for the changes!

**Pull request merged**
