### PR TITLE
Adds Sliders for Animations in Chapter 3

### PR DESCRIPTION
**Pull request by Rishav159**
This PR adds sliders for the animations in chapter 3.
It has the following advantages:
1. The animation can now be controlled by the readers. 
2. We will no longer have the problem of diagrams animating even when the user is not seeing it.

It adds a new file `globalHelpers.js`. We can have code that are common to all the chapters there.

### CODE REVIEW

**Comment by Rishav159** [comment]
Makes sense. Since it is supposed to be reused many times, maybe I could make it more modular and independent of the calling circumstances (Currently it uses d3 but maybe not all chapters will use it. But, we can be sure that JQuery for all chapters).
Also, it would be nice if the function actually creates the slider.

**Comment by Rishav159** [comment]
Regarding Documentation, will it be a good idea to follow the [jsdoc](https://github.com/jsdoc3/jsdoc) standards? It seems like a good style and also, we might later use jsdoc package to create documentation later.

**Comment by redblobgames** [comment]
I think it's fine to leave it d3, as it seems like it's the most popular choice among the people writing visualizations for aima.

I admit I don't know the javascript doc ecosystem these days, but jsdoc seems like a reasonable choice. The same syntax is used in esdoc.

**Comment by Rishav159** [comment]
Updated PR to include documentation for `globalHelpers.js`. The documentation is in jsdoc format. Later we can use the package to create documentation.

**Pull request merged**
