### PR TITLE
Adds visualization to demonstrate backtracking algorithm

### PR DESCRIPTION
**Pull request by Rishav159**
This PR adds a prototype for backtracking algorithm demonstration on the Australia Map coloring problem.
The FC and MAC heuristic is yet to be implemented. Also, I believe for this visualization, a slider or step control animation is a must as a lot of things is happening together.

(Not to be merged yet)

### CODE REVIEW

**Comment by redblobgames** [comment]
Looks cool! I agree, a slider/step control would be good, because it's happening too fast for me to see what's going on. Other things that could help:

* Highlight the newly added assignment somehow. Maybe an arrow pointing at the new assignment, or use a transition with a more saturated color fading to the regular color.
* Highlight the reason for backtracking - I'm not sure there's a good way to show conflicting assignments though. Or at least pause and display a message that there's no further possible assignments

**Comment by Rishav159** [comment]
Updated the PR.
- The heuristic is removed so the diagram can only focus on the backtracking concept.
- Added a slider and buttons to control the animation so the reader can see what is happening him
- The heading of the column of the recently assigned variable is highlighted for a short time to attract the user's attention and denote the assignment in that step.

The backtracking.js has MRV, Degree and LCV heuristic implemented for future algorithm. Other heuristics are still to be done.

**Comment by redblobgames** [comment]
Looks nice! Suggestions:

1. I like the highlighting of the most recently assigned variable. On the map, you could show this too. Try `stroke: black; stroke-width: 2px` (no transition needed) That will let the reader more easily see what changed from column N to column N+1. 
2. Right now the maps are clickable; I think you probably didn't mean to do this (it is sharing code with the earlier diagram)
3. Since you have the complete information for the slider, you can detect whether the *next* step is a backtracking step. I think that would be useful to display, so that the reader knows it is going to backtrack when they click Next

**Comment by Rishav159** [comment]
>Since you have the complete information for the slider, you can detect whether the next step is a backtracking step. I think that would be useful to display, so that the reader knows it is going to backtrack when they click Next

What would be a good way to show that the next step is a backtracking step? Maybe color the button with a separate color? Or a tooltip or simple text ?

**Comment by Rishav159** [comment]
Updated to take care of other points.
Also, highlights a column if its domain is completely empty.

**Comment by redblobgames** [comment]
I think simple text would work, maybe where “N uncolored states” is. That area would then have three possible messages:

* “N uncolored states” --> Next button will make one assignment
* “Impossible to make assignment” --> Next button will backtrack
* “Correct assignment” --> Next button does nothing because we are at the end

**Comment by Rishav159** [comment]
Update as per suggestions.

**Comment by redblobgames** [comment]
Looks good!

**Comment by redblobgames** [comment]
If you were doing it again (with the slider), would you still use the recursive generator? The main alternative I can think of is for the backtracking code to take a callback, and then the callback could record the state. You'd then be able to use a regular recursive function.

**Pull request merged**
