### PR TITLE
Add code for 6.1.1 CSP Map Colouring problem

### PR DESCRIPTION
**Pull request by kaiesh**
Needs friendly UI to be added

### CODE REVIEW

**Comment by Ghost---Shadow** [comment]
I have already made an index.html for chapter 6
http://ghost---shadow.github.io/aima-javascript/6-Constraint-Satisfaction-Problems/
I would Mr. @norvig to merge my pull request too.

**Comment by norvig** [comment]
This looks good, @kaiesh but there are conflicts; can you resolve?

**Comment by kaiesh** [comment]
Thanks @norvig, have resolved by merging the contributions from @Ghost---Shadow and adding my backtracking js to it.

**Comment by Ghost---Shadow** [comment]
@kaiesh Here is some small modifications to do before I can pull the request
1) The code to execute/visualize the algorithm should be in the c_backtracking.js, the backtracking.js should only contain code pertaining to the algorithm given in the book. Please split your code into two. The `index.html` will display the code in `backtracking.js` so that the viewer can see it side by side with the visualization for reference. 
2) jQuery is already included in `main.js` you need not include it again. 
3) I am new to npm but I think the `npm-debug.log` should be added to `.gitignore`

**Comment by kaiesh** [comment]
Hi @Ghost---Shadow, have cleaned up the files as suggested.

I didn't update the repo's gitignore, I think that should probably be a separate commit, but have removed the unintended log file from this pull request.

I still need to implement the canvas visual - but have kept the text output in the display box for now. Will update that slightly later.

Let me know if there's anything else!

**Pull request merged**
